name: Create Final Video

on:
  workflow_run:
    workflows: ["Generate Voiceover from Story"]
    types:
      - completed

permissions:
  contents: write

jobs:
  create_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GH_PAT }}

      - name: Install Git LFS and Pull LFS files
        run: |
          git lfs install
          git lfs pull

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Read version from yt.txt and create video
        run: |
          mkdir -p video_output

          if [ ! -f yt.txt ]; then
            echo "Error: yt.txt not found!"
            exit 1
          fi

          VERSION=$(cat yt.txt | tr -d '\n')
          IMAGE_FILE="Images/i${VERSION}.jpg"
          AUDIO_FILE="Audio/a${VERSION}.mp3"

          echo "Using image: $IMAGE_FILE"
          echo "Using audio: $AUDIO_FILE"

          if [ ! -f "$IMAGE_FILE" ]; then
            echo "Error: Image file $IMAGE_FILE not found!"
            exit 1
          fi

          if [ ! -f "$AUDIO_FILE" ]; then
            echo "Error: Audio file $AUDIO_FILE not found!"
            exit 1
          fi

          ffmpeg -loop 1 -i "$IMAGE_FILE" -i "$AUDIO_FILE" \
            -c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p \
            -vf scale=1920:1080 -shortest -movflags +faststart video_output/final_video.mp4

      - name: Set up Git identity
        run: |
          git config --global user.name "cowboycode9"
          git config --global user.email "cowboycode9@outlook.com"

      - name: Track video file with Git LFS
        run: |
          git lfs track "video_output/final_video.mp4"
          git add .gitattributes

      - name: Commit and push final video
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git stash --include-untracked
          git pull origin main --rebase
          git stash pop || true

          git add video_output/final_video.mp4
          timestamp=$(TZ="Asia/Kolkata" date +"%Y-%m-%d %H:%M:%S IST")
          git commit -m "Generated final video from version: $(cat yt.txt)" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
