name: Create Final Video

on:
  workflow_run:
    workflows: ["Generate Voiceover from Story"]
    types:
      - completed

permissions:
  contents: write

jobs:
  create-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GH_PAT }}

      - name: Install Git LFS and Pull LFS files
        run: |
          git lfs install
          git lfs pull

      - name: Download script_number artifact
        uses: actions/download-artifact@v3
        with:
          name: script-number

      - name: Read script_number
        id: get_script_number
        run: echo "SCRIPT_NUMBER=$(cat script_number.txt)" >> $GITHUB_OUTPUT

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Create video from image and audio
        run: |
          mkdir -p video_output
          SCRIPT_NUMBER="${{ steps.get_script_number.outputs.SCRIPT_NUMBER }}"

          IMAGE_FILE="Images/i${SCRIPT_NUMBER}.jpg"
          AUDIO_FILE="Audio/v${SCRIPT_NUMBER}.mp3"
          OUTPUT_VIDEO_FILE="video_output/v${SCRIPT_NUMBER}.mp4"

          if [ ! -f "$IMAGE_FILE" ]; then
            echo "Error: Image file $IMAGE_FILE not found!"
            exit 1
          fi

          if [ ! -f "$AUDIO_FILE" ]; then
            echo "Error: Audio file $AUDIO_FILE not found!"
            exit 1
          fi

          ffmpeg -loop 1 -i "$IMAGE_FILE" -i "$AUDIO_FILE" \
            -c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p \
            -vf scale=1920:1080 -shortest -movflags +faststart "$OUTPUT_VIDEO_FILE"

      - name: Set up Git identity
        run: |
          git config --global user.name "cowboycode9"
          git config --global user.email "cowboycode9@outlook.com"

      - name: Track video file with Git LFS
        run: |
          SCRIPT_NUMBER="${{ steps.get_script_number.outputs.SCRIPT_NUMBER }}"
          git lfs track "video_output/v${SCRIPT_NUMBER}.mp4"
          git add .gitattributes

      - name: Commit and push final video
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          SCRIPT_NUMBER="${{ steps.get_script_number.outputs.SCRIPT_NUMBER }}"
          git pull origin main --rebase
          git add "video_output/v${SCRIPT_NUMBER}.mp4"
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Generated final video: v${SCRIPT_NUMBER}.mp4 - ${timestamp}" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main

