name: Generate Image Prompt from Story

on:
  workflow_dispatch:

jobs:
  generate-prompt:
    runs-on: ubuntu-latest

    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Generate image prompt
        run: |
          python3 - <<EOF
          import os
          import requests
          import json

          url = "https://openrouter.ai/api/v1/chat/completions"
          headers = {
              "Authorization": f"Bearer {os.getenv('OPENROUTER_API_KEY')}",
              "Content-Type": "application/json",
              "HTTP-Referer": "https://your-site.com",
              "X-Title": "Image Prompt Creator"
          }

          STORY_FILE_PATH = "generated_story.txt"

          try:
              with open(STORY_FILE_PATH, "r", encoding="utf-8") as f:
                  story = f.read()
          except FileNotFoundError:
              print("Story file not found.")
              exit(1)

          prompt = (
              "You are a creative prompt engineer for AI-generated visuals.\n"
              "Given the story below, write a single detailed and vivid prompt that captures the most dramatic, cinematic, or emotional moment in the story, "
              "or a visual concept based on its title. Use visual keywords suitable for an image generation model like Midjourney or Stable Diffusion.\n"
              "Do not include any story explanations, just the raw image prompt.\n\n"
              f"STORY:\n{story}"
          )

          data = {
              "model": "nvidia/llama-3.3-nemotron-super-49b-v1:free",
              "messages": [
                  {"role": "user", "content": prompt}
              ]
          }

          response = requests.post(url, headers=headers, data=json.dumps(data))

          if response.status_code == 200:
              result = response.json()
              image_prompt = result["choices"][0]["message"]["content"]
              print("=== Generated Image Prompt ===")
              print(image_prompt.strip())
          else:
              print(f"Error {response.status_code}: {response.text}")
              exit(1)
          EOF
