name: Generate Voiceover from Story

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-voiceover:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install edge-tts nest_asyncio

    - name: Generate Voiceover with Edge TTS
      run: |
        python3 - <<EOF
        import nest_asyncio
        import asyncio
        import edge_tts

        VOICE = "ru-RU-DmitryNeural"
        INPUT_FILE = "generated_story.txt"
        OUTPUT_FILE = "generated_story.mp3"

        with open(INPUT_FILE, "r") as f:
            TEXT = f.read()

        async def amain():
            communicate = edge_tts.Communicate(TEXT, VOICE)
            await communicate.save(OUTPUT_FILE)

        nest_asyncio.apply()
        asyncio.run(amain())
        EOF

    - name: Set up Git identity
      run: |
        git config --global user.name "ansentase"
        git config --global user.email "samomsan7@gmail.com"

    - name: Commit and push voiceover
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git add generated_story.mp3
        timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        git commit -m "Generated voiceover: ${timestamp}" || echo "No changes to commit"
        git push https://x-access-token:${GH_PAT}@github.com/ansentase/scriptgen.git HEAD:main
