name: Generate Voiceover from Story

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-voiceover:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install edge-tts nest_asyncio

    - name: Generate Voiceover with Edge TTS
      run: |
        CURRENT_DATE=$(TZ="Asia/Kolkata" date +"%d%m%Y")
        export INPUT_FILE_PATH="Script/s${CURRENT_DATE}.txt"
        export OUTPUT_FILE_PATH="Audio/a${CURRENT_DATE}.mp3"

        echo "Looking for script: $INPUT_FILE_PATH"

        if [ ! -f "$INPUT_FILE_PATH" ]; then
          echo "Error: Input script file $INPUT_FILE_PATH not found!"
          exit 1
        fi

        mkdir -p Audio

        if [ -f "$OUTPUT_FILE_PATH" ]; then
          echo "Old audio file exists. Removing: $OUTPUT_FILE_PATH"
          rm "$OUTPUT_FILE_PATH"
        fi

        python3 - <<EOF
        import nest_asyncio
        import asyncio
        import edge_tts
        import os

        VOICE = "ru-RU-DmitryNeural"
        INPUT_FILE = os.getenv("INPUT_FILE_PATH")
        OUTPUT_FILE = os.getenv("OUTPUT_FILE_PATH")

        with open(INPUT_FILE, "r") as f:
            TEXT = f.read()

        async def amain():
            communicate = edge_tts.Communicate(TEXT, VOICE)
            await communicate.save(OUTPUT_FILE)

        nest_asyncio.apply()
        asyncio.run(amain())
        EOF

    - name: Set up Git identity
      run: |
        git config --global user.name "cowboycode9"
        git config --global user.email "cowboycode9@outlook.com"

    - name: Commit and push voiceover
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        # Safely handle remote changes
        git stash
        git pull origin main --rebase
        git stash pop || true

        git add Audio/*.mp3
        timestamp=$(TZ="Asia/Kolkata" date +"%Y-%m-%d %H:%M:%S IST")
        git commit -m "Generated voiceover: ${timestamp}" || echo "No changes to commit"
        git push https://x-access-token:${GH_PAT}@github.com/cowboycode9/automate.git HEAD:main
